# Vault environment connection details
vaults:
  - target:   true
    env:        minikube
    namespace:  "vault"
    k8s:        true
    host:       "localhost"
    port:       9200
    podname:    "vault-0"
    podport:    8200
    kubectx:    minikube

  - target:   false
    env:        "dev"
    namespace:  ""
    k8s:        false
    host:       "localhost"
    port:       8200
    podname:    ""
    kubectx:    ""
